### ISSUE TITLE
Duplicated values of rdfs:label

### ISSUE THREAD

**Issue by mereolog** [ontohgis/ontology#24]
There are 24 resources whose values of rdfs:label are not unique (within a language tag) - see below.

IMHO we should have some annotation property such that we can use to identify a resource.
Given the current status of the ontology the simplest solution would be to for all duplicates:
1. select the unique value
2. all other values move to some other annotation property, e.g., to skos:altLabel.

resource | language | labels
-- | -- | --
https://onto.kul.pl/ontohgis/administrative_system_30 | pl | Jednota Braci Czeskich w Polsce \| Unity of Brethren in Poland
https://onto.kul.pl/ontohgis/administrative_type_144 | ru | парафия \| приход
https://onto.kul.pl/ontohgis/administrative_type_150 | la | decanatus ruralis \| decanatus
https://onto.kul.pl/ontohgis/administrative_type_152 | pl | wikariat okręgowy (Kościół katolicki ob. łacińskiego) \| wikariat rejonowy (Kościół katolicki ob. łacińskiego)
https://onto.kul.pl/ontohgis/administrative_type_157 | ru | парафия \| приход
https://onto.kul.pl/ontohgis/administrative_type_167 | ru | клирос \| крылос
https://onto.kul.pl/ontohgis/administrative_type_169 | ru | парафия \| приход
https://onto.kul.pl/ontohgis/administrative_type_178 | de | Distrikt \| Superintendentur
https://onto.kul.pl/ontohgis/administrative_type_187 | en | Seniorat (Evangelical Augsburg Church in Prussia 1525-1817) \| seniorat
https://onto.kul.pl/ontohgis/administrative_type_199 |   | http://dbpedia.org/page/Superintendent_(ecclesiastical) \| https://de.wikipedia.org/wiki/Kirchenkreis
https://onto.kul.pl/ontohgis/administrative_type_199 | de | Kirchenkreis \| Superintendentur
https://onto.kul.pl/ontohgis/administrative_type_212 | de | Gemeinde \| Kirchspiel \| Pastorat \| Pfarre
https://onto.kul.pl/ontohgis/administrative_type_212 | pl | gmina (Kościół ewangelicki w Galicji 1781-1918) \| parafia \| zbór
https://onto.kul.pl/ontohgis/administrative_type_215 | de | General Superintendentur \| Konsistorium
https://onto.kul.pl/ontohgis/administrative_type_217 | pl | gmina (Żydzi w Rzeczypospolitej Obojga Narodów) \| kahał
https://onto.kul.pl/ontohgis/administrative_type_218 | pl | kahał okręgowy (Żydzi w Rzeczypospolitej Obojga Narodów) \| podokręg
https://onto.kul.pl/ontohgis/administrative_type_219 | pl | kahał okręgowy (Żydzi w Rzeczypospolitej Obojga Narodów) \| okręg
https://onto.kul.pl/ontohgis/administrative_type_220 | he | raszej ha-kehilot \| rosz ha-kehila
https://onto.kul.pl/ontohgis/administrative_type_220 | pl | kahał główny (Żydzi w Rzeczypospolitej Obojga Narodów) \| kahał na prawach ziemstwa \| kahał pryncypialny \| ziemstwo
https://onto.kul.pl/ontohgis/administrative_type_255 | en | general-governorate (Congress Poland (1867-1918)) \| land
https://onto.kul.pl/ontohgis/administrative_type_50 | ru | округ \| уезд
https://onto.kul.pl/ontohgis/administrative_type_86 | pl | hrabstwo (Elektorat Saksonii (1545-1805)) \| margrabstwo
https://onto.kul.pl/ontohgis/administrative_type_93 | de | Direktoriat \| Kreis
https://onto.kul.pl/ontohgis/object_10 | en | artefact \| artifact

**Comment by bszady** [comment]
some of these cases are errors, I will make a branch and correct it
