### ISSUE TITLE
Clarification of the inconsistency of "subclass of" and "forms part of"

### ISSUE THREAD

**Issue by bszady** [ontohgis/ontology#38]
In the descriptions of adinistrative unit types, a dual way of writing is used. 
In most cases the scheme is used: 
- Subclass of 'forms part of' some 'parent unit type'.

![image](https://github.com/ontohgis/ontology/assets/21007174/c75f6559-8d85-4985-8d49-4665bbe6865f)

Sometimes it occurs:
- Subclass of 'parent unit type'. 
![image](https://github.com/ontohgis/ontology/assets/21007174/935b4cf0-3616-49a2-abd4-4d5c936619a4)

Is this notation correct and is it not necessary to standardise it by writing it everywhere in the same way, e.g. 'subclass of'?
- Subclass of 'parent unit type'.

**Comment by mereolog** [comment]
@bszady, this depends on a particular case. An admin unit type XYZ can be:

1.  a subclass of class, e.g., another admin unit type - then every instance of the former _is_ an instance of the latter
2. a part (in the sense of [partonomic inclusion](https://www.researchgate.net/publication/239215672_Individuals_Universals_Collections_On_the_Foundational_Relations_of_Ontology)) of another class, e.g., another admin unit type - then every instance of the former _is part of an instance_ of the latter.

The decision which of these two possibilities is the case belongs to the domain expert.
(In principle both 1 and 2 can occur at the same time, but it is rare.)

**Comment by bszady** [comment]
@mereolog 
I think I understand. But please still briefly confirm with examples: 
- the class urban district is a subclass of the class district (case 1) (example: the instance Lublin urban district belongs to the class urban district and thus to the class district) 
- the class rural district is a subclass of the class district (case 1) (example: the instance Lubelski rural district belongs to the class rural district and thus to the class district)
- the class rural district is a part of the class voivodship (case 2) (e.g. an instance of Lubelski rural district is a part of the instance Lubelskie voivodship, which belongs to the class voivodship)
- the class urban district is a part of the class voivodship (case 2) (e.g. an instance of Lublin urban district is a part of an instance of Lubelskie voivodship, which belongs to the class voivodship)
and
- the class district (understood as a set or collection of the classes rural district and urban district) is a part of the class województwo (case 2)

**Comment by mereolog** [comment]
Yes, these examples sound fine - you just need to bear in mind that in case 2 one class is not part of another class simpliciter, but only in the sense of instances of the former being parts of some instances of the latter.

**Comment by bszady** [comment]
Yes, I am aware of that. My doubt was raised by the use of 'is part of' in relation to classes rather than instances. The explanation given indicates that the solution used is deliberate and intentional and not the result of an error. I am closing this issue.
