### ISSUE TITLE
The problem of two types of subclasses in admin units

### ISSUE THREAD

**Issue by bszady** [ontohgis/ontology#40]
The problem of two types of subclasses. This task is related to the issue [38](https://github.com/ontohgis/ontology/issues/38).
Clarify whether it is correct to maintain two types of subclasses for administrative unit types. 

Situation 1: concerns the classical subordination: e.g. municipality, county, province or parish, decanate, archdeaconry, diocese. A lower-order unit is lower in the hierarchy than a higher-order unit. It is expressed in the ontology by the syntax "SubClass of 'forms part of' some [superior unit]", e.g. Kreis is part of Regierungsbezirk

Code:

ontohgis:administrative_type_39
	a owl:Class ;
	rdfs:subClassOf
		ontohgis:object_3014 ,
		[
			a owl:Restriction ;
			owl:onProperty <http://www.cidoc-crm.org/cidoc-crm/P46i_forms_part_of> ;
			owl:someValuesFrom ontohgis:administrative_type_42 ;
		]
		;
	rdfs:label
		"Kreis (Königreich Preußen (1806-1919))"@de ,
		"district (The Kingdom of Prussia (1806-1919))"@en ,
		"district (The Kingdom of Prussia (1806-1919))"@en
		;
	<http://www.w3.org/2004/02/skos/core#altLabel> "county"@en ;
	ontohgis:isDefinedByEntity ontohgis:administrative_system_7 ;
	ontohgis:isSymbolisedByMeansOf ontohgis:map_symbol_30 ;
	ontohgis:seeAlsoIRI
		"http://gov.genealogy.net/types.owl#32" ,
		"https://www.wikidata.org/wiki/Q106658"
		;
	.

Situation 2: There is also a different kind of dependency in the ontology, e.g. a district (Kreis) (general category) includes an urban district (Stadtkreis) and a rural district (Landkreis), which are more types of districts within the parent category. The whole area was covered by urban and rural districts as units of the same level. I have a doubt whether the urban district and the rural district are subclasses or just two types in this single level class.

Code: 
ontohgis:administrative_type_40
	a owl:Class ;
	rdfs:subClassOf ontohgis:administrative_type_39 ;
	rdfs:label
		"Landkreis"@de ,
		"rural district (The Kingdom of Prussia (1806-1919))"@de ,
		"rural district (The Kingdom of Prussia (1806-1919))"@en
		;
	ontohgis:isDefinedByEntity ontohgis:administrative_system_7 ;
	ontohgis:isSymbolisedByMeansOf ontohgis:map_symbol_30 ;
	ontohgis:seeAlsoIRI
		"http://gov.genealogy.net/types.owl#32" ,
		"https://www.wikidata.org/wiki/Q106658"
		;
	.

ontohgis:administrative_type_41
	a owl:Class ;
	rdfs:subClassOf ontohgis:administrative_type_39 ;
	rdfs:label
		"Stadtkreis"@de ,
		"urban district (The Kingdom of Prussia (1806-1919))"@de ,
		"urban district (The Kingdom of Prussia (1806-1919))"@en
		;
	rdfs:comment "Equivalent to a land district but no longer divided into smaller aldermanships"@en ;
	ontohgis:isDefinedByEntity ontohgis:administrative_system_7 ;
	ontohgis:isSymbolisedByMeansOf ontohgis:map_symbol_30 ;
	ontohgis:seeAlsoIRI "http://gov.genealogy.net/types.owl#32" ;
	.

**Comment by mereolog** [comment]
I am not sure what the issue here is, but looking at the labels of administrative_type_41 and administrative_type_40 I do not see any modelling error. The ontology now says (implicitly) that a district can be either in a rural area or in an urban area - this looks correct to me, but this is a layman's point of view and all such decisions should be made by a domain expert.

**Comment by bszady** [comment]
I am closing this issue because the essence of the problem is in the issue [38](https://github.com/ontohgis/ontology/issues/38)
